### ISSUE TITLE
seemingly random 'expireTime must be after the current time' error

### ISSUE THREAD

**Issue by ashishmadeti** [jasonsims/aws-cloudfront-sign#16]
Sometimes my app, which uses 'aws-cloudfront-sign' to generate signed urls crash with the following log:
        throw message;      
              ^
Error: expireTime must be after the current time
    at assert (<folder>/sails/node_modules/aws-cloudfront-sign/lib/CannedPolicy.js:60:11)
    at CannedPolicy._validate (<folder>/sails/node_modules/aws-cloudfront-sign/lib/CannedPolicy.js:48:3)
    at CannedPolicy.toJSON (<folder>/sails/node_modules/aws-cloudfront-sign/lib/CannedPolicy.js:19:8)
    at Object.getSignedUrl (<folder>/sails/node_modules/aws-cloudfront-sign/lib/cloudfrontUtil.js:30:22)
    at signedUrlForOrder (<folder>/sails/api/controllers/AppController.js:34:19)
    at <folder>/sails/api/controllers/AppController.js:228:56
    at <folder>/sails/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/collection/query.js:164:5
    at Cursor.nextObject (<folder>/sails/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/cursor.js:753:5)
    at commandHandler (<folder>/sails/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/cursor.js:727:14)
    at <folder>/sails/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/db.js:1874:9
    at Server.Base._callHandler (<folder>/sails/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at <folder>/sails/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
    at MongoReply.parseBody (<folder>/sails/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (<folder>/sails/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
    at emit (events.js:95:17)
    at null.<anonymous> (<folder>/sails/node_modules/sails-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
    at emit (events.js:98:17)

But this is happening only sometimes (very very rarely), most of the times it is working fine.
my options look like this:
var signingParams = {
  keypairId: <key>,
  privateKeyPath: <key>,
  expireTime: (new Date().getTime()) + 86400000
}

**Comment by OJcode14** [comment]
You need to create the object each time the signed url is requested.

**Comment by ashishmadeti** [comment]
Thank you, that solved the issue
